{{- if .Values.cnpg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "paperless-ngx.fullname" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
  {{- with .Values.cnpg.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  instances: {{ .Values.cnpg.instances }}
  storage:
    size: {{ .Values.cnpg.storage.size }}
    {{- with .Values.cnpg.storage.storageClass }}
    storageClass: {{ . }}
    {{- end }}
  {{- with .Values.cnpg.parameters }}
  postgresql:
    parameters:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- with .Values.cnpg.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  logLevel: {{ .Values.cnpg.logLevel }}
  primaryUpdateStrategy: {{ .Values.cnpg.primaryUpdateStrategy }}
  bootstrap:
    initdb:
      database: {{ .Values.cnpg.database }}
      owner: {{ .Values.cnpg.owner }}
{{- end }}
