{{- if .Values.gotenberg.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-gotenberg
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: gotenberg
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "paperless-ngx.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gotenberg
  template:
    metadata:
      labels:
        {{- include "paperless-ngx.labels" . | nindent 8 }}
        app.kubernetes.io/component: gotenberg
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: gotenberg
          image: "{{ .Values.gotenberg.image.repository }}:{{ .Values.gotenberg.image.tag }}"
          imagePullPolicy: {{ .Values.gotenberg.image.pullPolicy }}
          {{- with .Values.gotenberg.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          {{- with .Values.gotenberg.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
