apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-secret-key
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  secret-key: {{ .Values.paperless.secretKey | default (randAlphaNum 50) | b64enc | quote }}
